# Generated by Django 5.2.7 on 2025-12-31 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CameraSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iso_speed",
                    models.CharField(
                        choices=[
                            ("Auto", "Auto"),
                            ("100", "100"),
                            ("200", "200"),
                            ("400", "400"),
                            ("800", "800"),
                            ("1600", "1600"),
                            ("3200", "3200"),
                            ("6400", "6400"),
                        ],
                        default="Auto",
                        max_length=10,
                    ),
                ),
                (
                    "shutter_speed",
                    models.CharField(
                        choices=[
                            ("bulb", "bulb"),
                            ("30", "30"),
                            ("25", "25"),
                            ("20", "20"),
                            ("15", "15"),
                            ("13", "13"),
                            ("10.3", "10.3"),
                            ("8", "8"),
                            ("6.3", "6.3"),
                            ("5", "5"),
                            ("4", "4"),
                            ("3.2", "3.2"),
                            ("2.5", "2.5"),
                            ("2", "2"),
                            ("1.6", "1.6"),
                            ("1.3", "1.3"),
                            ("1", "1"),
                            ("0.8", "0.8"),
                            ("0.6", "0.6"),
                            ("0.5", "0.5"),
                            ("0.4", "0.4"),
                            ("0.3", "0.3"),
                            ("1/4", "1/4"),
                            ("1/5", "1/5"),
                            ("1/6", "1/6"),
                            ("1/8", "1/8"),
                            ("1/10", "1/10"),
                            ("1/13", "1/13"),
                            ("1/15", "1/15"),
                            ("1/20", "1/20"),
                            ("1/25", "1/25"),
                            ("1/30", "1/30"),
                            ("1/40", "1/40"),
                            ("1/50", "1/50"),
                            ("1/60", "1/60"),
                            ("1/80", "1/80"),
                            ("1/100", "1/100"),
                            ("1/125", "1/125"),
                            ("1/160", "1/160"),
                            ("1/200", "1/200"),
                            ("1/250", "1/250"),
                            ("1/320", "1/320"),
                            ("1/400", "1/400"),
                            ("1/500", "1/500"),
                            ("1/640", "1/640"),
                            ("1/800", "1/800"),
                            ("1/1000", "1/1000"),
                            ("1/1250", "1/1250"),
                            ("1/1600", "1/1600"),
                            ("1/2000", "1/2000"),
                            ("1/2500", "1/2500"),
                            ("1/3200", "1/3200"),
                            ("1/4000", "1/4000"),
                        ],
                        default="1/60",
                        max_length=10,
                    ),
                ),
                (
                    "aperture",
                    models.CharField(
                        choices=[
                            ("4", "4"),
                            ("4.5", "4.5"),
                            ("5", "5"),
                            ("5.6", "5.6"),
                            ("6.3", "6.3"),
                            ("7.1", "7.1"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("13", "13"),
                            ("14", "14"),
                            ("16", "16"),
                            ("18", "18"),
                            ("20", "20"),
                            ("22", "22"),
                            ("25", "25"),
                        ],
                        default="8",
                        max_length=5,
                    ),
                ),
                (
                    "white_balance",
                    models.CharField(
                        choices=[
                            ("Auto", "Auto"),
                            ("Daylight", "Daylight"),
                            ("Shadow", "Shadow"),
                            ("Cloudy", "Cloudy"),
                            ("Tungsten", "Tungsten"),
                            ("Fluorescent", "Fluorescent"),
                            ("Flash", "Flash"),
                            ("Manual", "Manual"),
                        ],
                        default="Auto",
                        max_length=20,
                    ),
                ),
                (
                    "image_format",
                    models.CharField(
                        choices=[
                            ("L", "L"),
                            ("cL", "cL"),
                            ("M", "M"),
                            ("cM", "cM"),
                            ("S1", "S1"),
                            ("cS1", "cS1"),
                            ("S2", "S2"),
                            ("S3", "S3"),
                            ("RAW + L", "RAW + L"),
                            ("RAW", "RAW"),
                        ],
                        default="L",
                        max_length=10,
                    ),
                ),
                (
                    "drive_mode",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Continuous", "Continuous"),
                            ("Timer 10 sec", "Timer 10 sec"),
                            ("Timer 2 sec", "Timer 2 sec"),
                            ("Continuous timer", "Continuous timer"),
                        ],
                        default="Single",
                        max_length=20,
                    ),
                ),
                (
                    "metering_mode",
                    models.CharField(
                        choices=[
                            ("Evaluative", "Evaluative"),
                            ("Partial", "Partial"),
                            ("Center-weighted average", "Center-weighted average"),
                        ],
                        default="Evaluative",
                        max_length=30,
                    ),
                ),
                (
                    "picture_style",
                    models.CharField(
                        choices=[
                            ("Auto", "Auto"),
                            ("Standard", "Standard"),
                            ("Portrait", "Portrait"),
                            ("Landscape", "Landscape"),
                            ("Neutral", "Neutral"),
                            ("Faithful", "Faithful"),
                            ("Monochrome", "Monochrome"),
                            ("User defined 1", "User defined 1"),
                            ("User defined 2", "User defined 2"),
                            ("User defined 3", "User defined 3"),
                        ],
                        default="Auto",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Camera Setting",
                "verbose_name_plural": "Camera Settings",
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("path", models.CharField(default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("ip", models.CharField(max_length=15)),
                ("device_id", models.CharField(max_length=5)),
                ("cameras", models.JSONField(default={})),
                ("statistics", models.JSONField(default={})),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FlashSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delay",
                    models.IntegerField(
                        default=0, help_text="Flash delay in milliseconds"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Flash Setting",
                "verbose_name_plural": "Flash Settings",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("path", models.CharField(default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("path", models.CharField(max_length=200)),
                ("size", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.collection"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="collection",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.project"
            ),
        ),
    ]
